### PR TITLE
Allow to set headers on request object in #recognize_path

### PR DESCRIPTION
**Pull request by lukaszx0**
Helpful when testing routes with host/protocol constraint:

``` ruby
Rails.application.routes.recognize_path('/foo/bar', :method => 'get', 'HTTPS' => 'on', HTTP_HOST => example.com)
```

/cc @tamird

### CODE REVIEW

**Comment by tamird** [comment]
fwiw i was able to work around this with a fully specified route (rather than a path)

**Comment by lukaszx0** [comment]
Interesting. Do we still want/need it then?

**Comment by tamird** [comment]
not for this fork. might be useful upstream?

**Comment by lukaszx0** [comment]
Yep, I'll work on that later.

**Pull request closed without merging**
