### PR TITLE
Backport mime-type parsing fixes

### PR DESCRIPTION
**Pull request by lukaszx0**
Backport fixes to mime type parsing which are causing `ActiveRecord::MissingTemplate` exceptions when we're being crawled by googlebot and others.

@tamird @JackDanger @ecin

### CODE REVIEW

**Comment by ecin** [comment]
@strzalek is this missing specs for `text/*` and `application/*`?

**Comment by tamird** [comment]
:+1:

**Comment by tamird** [comment]
d'oh, yeah, seems some specs are missing: https://github.com/scottwb/rails/blob/3b203f7cb6c54963f74d1ab4237bf7403cc3bf8f/actionpack/test/dispatch/mime_type_test.rb#L32-L58

**Comment by lukaszx0** [comment]
Yep, thanks guys. I've pushed updated commit.

**Comment by ggilder** [comment]
:+1:

**Comment by lukaszx0** [comment]
Had to backport `MimeType.unregister` and fix test pollution. Should be green now.

**Pull request merged**
