### PR TITLE
Reverse include_password defaults for dbconsole

### PR DESCRIPTION
**Pull request by lukaszx0**
Unfortunately there's no way to configure it. I'll think about some nice way to introduce it (maybe something like `config.console.dbconsole.include_password =` in application.rb?) and send PR for upstream rails. 

Meanwhile if we want to have `-p` by default, we need to use this hack :see_no_evil: 

@square/railsfork-contributors

### CODE REVIEW

**Comment by tamird** [comment]
:+1: LGTM

**Comment by rafaelfranca** [comment]
I think it even make sense change the default on upstream too.

**Comment by lukaszx0** [comment]
Thanks @rafaelfranca for dropping by. I'll send PR to `rails/rails` today.

**Comment by lukaszx0** [comment]
https://github.com/rails/rails/pull/15104

**Pull request merged**
