### PR TITLE
Missing indices are errors

### PR DESCRIPTION
**Pull request by tamird**
@strzalek @JackDanger @robolson

### CODE REVIEW

**Comment by bradseiler** [comment]
LGTM

**Comment by tamird** [comment]
@bradseiler

**Comment by lukaszx0** [comment]
Won't it break any tests? Let's port them as well: https://github.com/rails/rails/commit/37de59eacf8f6478e866309615af7381d41a5a14

**Comment by tamird** [comment]
Yup, you're right, fixed.

**Comment by lukaszx0** [comment]
Thanks! LGTM on green :+1:

**Pull request merged**
