### PR TITLE
Fix requirements!

### PR DESCRIPTION
**Pull request by tamird**
@rudle @strzalek this fixes our url generation woes

### CODE REVIEW

**Comment by rudle** [comment]
less string eval implies more :grinning:

**Comment by lukaszx0** [comment]
For the record, this hasn't been fixed in `3.1` release so we'll need to port it to `3-1-square` as well.

**Comment by tamird** [comment]
will force push a better commit message after this is green

**Comment by lukaszx0** [comment]
Unfortunately looks like it hasn't been fixed until `4.x` - https://github.com/rails/rails/commit/9b4514c3b8ecfbc40a44dbd4c2ebd4ce67f4a459

**Pull request merged**
