### PR TITLE
Use HashWithIndifferentAccess for reflections

### PR DESCRIPTION
**Pull request by tamird**
This prevents a bug where we try to access reflections with string
keys rather than symbols.

### CODE REVIEW

**Comment by tamird** [comment]
@square/railsfork-contributors

**Comment by tamird** [comment]
This was accidentally fixed upstream in https://github.com/rails/rails/commit/1f31488499111fdfce79d8dc1cc8fb008f7cdb25 which is not yet released. @laurocaetano @tenderlove

**Comment by lukaszx0** [comment]
:+1: on :green_apple:

**Comment by tamird** [comment]
cc @jjowdy

**Comment by jjowdy** [comment]
:+1:

**Pull request merged**
