### PR TITLE
Backport ActiveSupport::MessageEncryptor/Verifier from Rails 4.0.4

### PR DESCRIPTION
**Pull request by tarcieri**
This backports the versions of these classes from upstream rails at 051d289030a6cb86590cd1b619eae1879b48458a

The most notable differences are the ability to use non-Marshal serializers and also specify a signature key which is distinct from the encryption key. Otherwise these are backwards compatible with their Rails 2.x counterparts. The implementation is also, in general, less wonky (see the old constant time comparison code vs the new code)

Using a non-Marshal serializer (e.g. the provided NullSerializer, or JSONSerializer) will make interop with non-Rails things easier.

### CODE REVIEW

**Comment by lukaszx0** [comment]
It broke the build: https://travis-ci.org/square/rails/builds/21026978#L790

@nealharris could you please take a look as well?

**Comment by tarcieri** [comment]
Looks like this is the problem:

``` rails
ActiveSupport::MessageVerifier.new(SessionSecret, 'SHA1')
```

For backwards compatibility, the second argument, if a string, should be interpreted as the digest algorithm name.

Pushing a fix...

**Comment by tarcieri** [comment]
@strzalek looking better now... wondering if I should do the same fix for `ActiveSupport::MessageEncryptor` as it used to support the cipher name as a string as the second argument

**Comment by lukaszx0** [comment]
If that won't be hard to do, I'd say yes. One more thing to keep in mind when back porting stuff from > 3.0 releases is that we want to keep it compatible with 3.0.x release to which we're about to migrate. So for example back ported feature X from 4.0 to 2.3 should be compatible with 3.0 :sparkles:

**Comment by lukaszx0** [comment]
> So for example back ported feature X from 4.0 to 2.3 should be compatible with 3.0

All right. I just realized that what I've just wrote is a bit abstract and hard to achieve in most cases.

Maybe let's not bother about that aspect. We'll work on those kind of issues separately on `3-0-square` branch.

**Comment by tarcieri** [comment]
Hmm, supporting the Ruby 2.3 method signature for `MessageEncryptor` is nontrivial because Ruby 4.0 recognizes the following signatures:

``` ruby
MessageEncryptor.new(encryption_key)

MessageEncryptor.new(encryption_key, signing_key)

MessageEncryptor.new(encryption_key, options = {})

MessageEncryptor.new(encryption_key, signing_key, options={})
```

...so it's not possible to disambiguate the cipher name from the signing key. However unless we're actively using MessageEncryptor elsewhere in Rails 2.x (at a quick grep we're not) I don't think it's too important to support the Rails 2.x method signature.

We can definitely carry these changes forward into Rails 3.x no problem. They're backwards compatible (Rails 3 supports two of the four method signatures listed above, i.e. the ones without a signing_key)

**Comment by lukaszx0** [comment]
I agree, let's leave it like this then :+1:

**Pull request merged**
