### PR TITLE
Add dbconsole support for multidb shards

### PR DESCRIPTION
**Pull request by ggilder**
@tamird @strzalek @eam

### CODE REVIEW

**Comment by ggilder** [comment]
FYI the test here is gross but it's also throwaway because it'll be completely different for 4.0

**Comment by lukaszx0** [comment]
This change is very custom to our setup, not sure if I like it. This means that we'd need to forward port it for every rails release and also "locks" us for using multidb.

Not sure if I like this.

**Comment by ggilder** [comment]
I agree with those concerns in general — although the change here is fairly minimal and is probably pretty easy to forward port. I'm open to alternate approaches though — do you think we should just override this script in the application?

**Comment by lukaszx0** [comment]
I think I would favor custom wrapper script eg. `sqconsole` doing monkey patching to customize dbconsole behavior to our needs.

**Pull request closed without merging**
