### PR TITLE
Add :conditions option to uniqueness validator

### PR DESCRIPTION
**Pull request by tamird**
Wonder if tests will pass! @square/railsfork-contributors

### CODE REVIEW

**Comment by tamird** [comment]
tests didnt pass yet =/

**Comment by JackDanger** [comment]
Gah. I misread the UI :(

**Comment by JackDanger** [comment]
Welp. I guess I coyboy'd the crap outta this.

**Comment by tamird** [comment]
they might pass! i'm hopeful.

**Comment by tamird** [comment]
passed! nice

**Comment by JackDanger** [comment]
Nice work, @tamird!
Try harder next time, @JackDanger

**Comment by lukaszx0** [comment]
Late to the party but looks good :+1:

**Pull request merged**
